export const skillGroups = Object.freeze([
  Object.freeze({
    id: 'frontend',
    label: 'Frontend',
    skills: Object.freeze([
      'React',
      'JavaScript (ES6+)',
      'HTML5',
      'CSS3',
      'Tailwind CSS',
      'React Router',
      'Context API',
      'Vite',
    ]),
  }),
  Object.freeze({
    id: 'backend',
    label: 'Backend',
    skills: Object.freeze([
      'Node.js',
      'Express.js',
      'REST APIs',
      'JWT Authentication',
      'Mongoose',
    ]),
  }),
  Object.freeze({
    id: 'cloud-infrastructure',
    label: 'Cloud & Infrastructure',
    skills: Object.freeze([
      'AWS',
      'Amazon EC2',
      'Amazon S3',
      'AWS Lambda',
      'AWS Glue',
      'IAM',
      'VPC',
      'Elastic Load Balancing',
      'Auto Scaling',
      'CloudWatch',
      'Amazon SNS',
      'MongoDB Atlas',
    ]),
  }),
  Object.freeze({
    id: 'deployment-tools',
    label: 'Deployment & Tools',
    skills: Object.freeze(['Git', 'GitHub', 'Vercel', 'Render', 'Postman']),
  }),
  Object.freeze({
    id: 'engineering-practices',
    label: 'Engineering Practices',
    skills: Object.freeze([
      'Responsive Design',
      'Accessibility',
      'Component Architecture',
      'REST API Design',
      'Performance Optimization',
      'Debugging',
      'Cloud Architecture',
      'System Documentation',
      'API Integration',
    ]),
  }),
])
